version: '2.1'

services:

  alpine:
    build: ./alpine
    privileged: true
    labels:
      io.balena.features.balena-api: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.dbus: 1
      io.balena.features.kernel-modules: 1

  debian:
    build: ./debian
    privileged: true
    labels:
      io.balena.features.balena-api: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.dbus: 1
      io.balena.features.kernel-modules: 1